checking if there is a db url

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,15 @@ jobs:
         with:
           node-version: 22
 
+      - name: check db is present
+        run: |
+          if [ -z "$DATABASE_URL" ]; then
+            echo "DATABASE_URL is missing"
+            exit 1
+          else
+            echo "DATABASE_URL is present"
+          fi
+
       - name: Install dependencies
         run: npm ci
 
